name: webfeed
version: 0.7.1
description: webfeed is a dart package for parsing RSS and Atom feeds. Media, DublinCore, iTunes, Syndication namespaces are also supported.
homepage: https://github.com/witochandra/webfeed

environment:
  sdk: '^3.5.1'

dependencies:
  xml: ^6.5.0
  intl: ^0.20.2

dev_dependencies:
  http: ^1.4.0
  test: ^1.24.3
